# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

# Groups
- id: primary-standalone-ceph-mon
  type: group
  version: 2.1.0
  role: [primary-standalone-ceph-mon]
  requires: [controller]
  required_for: [ceph-osd]
  tasks: [ceph-mon,hiera-override-for-standalone-ceph,firewall,hiera,tools,netconfig,connectivity_tests,globals,fuel_pkgs,logging,hosts,apache,openstack-haproxy,ssl-add-trust-chain, setup_repositories]
  parameters:
    strategy:
      type: one_by_one

- id: standalone-ceph-mon
  type: group
  version: 2.1.0
  role: [standalone-ceph-mon]
  requires: [primary-standalone-ceph-mon]
  required_for: [deploy_end]
  tasks: [ceph-mon,hiera-override-for-standalone-ceph,firewall,hiera,tools,netconfig,connectivity_tests,globals,fuel_pkgs,logging,hosts,apache,openstack-haproxy,ssl-add-trust-chain, setup_repositories]
  parameters:
    strategy:
      type: parallel

#- id: rados-virtual_ips
#  type: puppet
#  version: 2.1.0
#  groups: /(primary-)?standalone-ceph-mon$/
#  required_for: [deploy_end]
#  requires: [primary-cluster,cluster]
#  condition:
#    yaql_exp: &rados_virtual_ip > 
#    "changedAny($.network_metadata, $.network_scheme, $.roles) and $.storage.objects_ceph"
#  parameters:
#    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/virtual_ips/virtual_ips.pp
#    puppet_modules: /etc/puppet/modules
#    timeout: 3600
#  test_post:
#    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/virtual_ips/virtual_ips_post.rb
 
#- id: primary-ceph-radosgw
#  type: skipped
#
#- id: ceph-radosgw
#  type: skipped

#- id: primary-ceph-radosgw
#  version: 2.1.0
#  type: puppet
#  groups: [primary-standalone-ceph-mon]
#  required_for: [deploy_end, controller_remaining_tasks]
#  requires: [apache, ceph-mon, primary-ceph-mon]
#  parameters:
#    puppet_manifest: radosgw.pp
#    puppet_modules: .
#    timeout: 3600
#  test_pre:
#    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/ceph/radosgw_pre.rb
#  test_post:
#    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/ceph/radosgw_post.rb
#
#- id: ceph-radosgw
#  version: 2.1.0
#  type: puppet
#  groups: [standalone-ceph-mon]
#  required_for: [deploy_end, controller_remaining_tasks]
#  requires: [apache, ceph-mon, primary-ceph-mon]
#  parameters:
#    puppet_manifest: radosgw.pp
#    puppet_modules: .
#    timeout: 3600
#  cross-depends:
#    - name: primary-ceph-radosgw
#  test_pre:
#    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/ceph/radosgw_pre.rb
#  test_post:
#    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/ceph/radosgw_post.rb


- id: ceph-radosgw
  type: skipped
  version: 2.1.0

- id: primary-ceph-radosgw
  type: skipped
  version: 2.1.0

#- id: openstack-haproxy-radosgw
#  type: skipped
#
#- id: swift-keystone
#  type: skipped

- id: ceph-compute
  type: skipped
  version: 2.1.0

- id: enable_rados
  type: skipped
  version: 2.1.0

- id: radosgw-keystone
  type: skipped
  version: 2.1.0

# Override hiera for at least primary_mon value
- id: hiera-override-for-standalone-ceph
  type: puppet
  version: 2.1.0
  groups: [ceph-osd,primary-standalone-ceph-mon,standalone-ceph-mon,compute,primary-controller,controller]
  requires: [globals]
  required_for: [task-standalone-ceph-mon,top-role-ceph-osd,deploy_end]
  parameters:
    puppet_manifest: 'hiera-override.pp'
    puppet_modules: 'modules:/etc/puppet/modules'
    timeout: 120

# Standalone mons
- id: ceph-mon
  type: puppet
  version: 2.1.0
  groups: [standalone-ceph-mon]
  required_for: [deploy_end]
  requires: [connectivity_tests,hiera,globals]
  cross-depends:
    - name: ceph-mon
      role: primary-standalone-ceph-mon
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/ceph/mon.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: primary-ceph-mon
  type: puppet
  version: 2.1.0
  groups: [primary-standalone-ceph-mon,standalone-ceph-mon]
  required_for: [deploy_end]
  requires: [connectivity_tests,hiera,globals]
  cross-depends:
    - name: ceph-mon
      role: primary-standalone-ceph-mon
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/ceph/mon.pp
    puppet_modules: /etc/puppet/modules
    #puppet_manifest: 'mon.pp'
    #puppet_modules: 'modules:/etc/puppet/modules'
    timeout: 3600
#RadosGW deployment
#- id: cluster-for-standalone-ceph
#  type: puppet
#  version: 2.0.0
#  groups: [primary-standalone-ceph-mon,standalone-ceph-mon]
#  required_for: [virtual_ips,deploy_end]
#  requires: [hosts, firewall, deploy_start]
#  parameters:
#    puppet_manifest: 'cluster.pp'
#    puppet_modules: 'modules:/etc/puppet/modules'
#    timeout: 3600
#
#- id: cluster-haproxy-for-standalone-ceph
#  type: puppet
#  version: 2.1.0
#  groups: [primary-standalone-ceph-mon,standalone-ceph-mon]
#  required_for: [deploy_end]
#  requires: [deploy_start, cluster-for-standalone-ceph, virtual_ips]
#  parameters:
#    puppet_manifest: 'cluster-haproxy.pp'
#    puppet_modules: 'modules:/etc/puppet/modules'
#    timeout: 3600

#POSTDEPLOYMENT
#- id: ceph_create_pools-for-standalone-ceph
#  type: puppet
#  role: [primary-standalone-ceph-mon,standalone-ceph-mon]
#  requires: [post_deployment_start]
#  required_for: [ceph_ready_check-for-standalone-ceph]
#  condition: "settings:storage.objects_ceph.value == true or settings:storage.images_ceph.value == true or settings:storage.volumes_ceph.value == true or settings:storage.ephemeral_ceph.value == true"
#  parameters:
#    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/ceph/ceph_pools.pp
#    puppet_modules: /etc/puppet/modules
#    timeout: 3600
#    cwd: /

#- id: ceph_ready_check-for-standalone-ceph
#  type: shell
#  role: [primary-standalone-ceph-mon]
#  condition: "settings:storage.objects_ceph.value == true or settings:storage.images_ceph.value == true or settings:storage.volumes_ceph.value == true or settings:storage.ephemeral_ceph.value == true"
#  requires: [post_deployment_start]
#  required_for: [enable_rados-for-standalone-ceph, upload_cirros]
#  parameters:
#    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/ceph/ceph_ready_check.rb
#    timeout: 1800

- id: ceph_client
  type: puppet
  version: 2.1.0
  role: [primary-controller,controller]
  requires: [post_deployment_start]
  required_for: [ceph_create_pools,post_deployment_end]
  condition: "settings:storage.objects_ceph.value == true or settings:storage.images_ceph.value == true or settings:storage.volumes_ceph.value == true or settings:storage.ephemeral_ceph.value == true"
  parameters:
    puppet_manifest: 'ceph_client.pp'
    puppet_modules: 'modules:/etc/puppet/modules'
    timeout: 3600

#- id: dns-client-for-standalone-ceph
#  type: puppet
#  version: 2.1.0
#  role: [primary-standalone-ceph-mon,standalone-ceph-mon]
#  requires: [post_deployment_start]
#  required_for: [ntp-client-for-standalone-ceph]
#  parameters:
#    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/dns/dns-client.pp
#    puppet_modules: /etc/puppet/modules
#    timeout: 3600
#    cwd: /
#
#- id: ntp-client-for-standalone-ceph
#  type: puppet
#  version: 2.1.0
#  role: [primary-standalone-ceph-mon,standalone-ceph-mon]
#  requires: [dns-client-for-standalone-ceph]
#  required_for: [post_deployment_end]
#  parameters:
#    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/ntp/ntp-client.pp
#    puppet_modules: /etc/puppet/modules
#    timeout: 3600
#    cwd: /

#- id: configure-default-route-ceph-mon
#  type: puppet
#  version: 2.0.0
#  role: [primary-standalone-ceph-mon,standalone-ceph-mon]
#  requires: [post_deployment_start]
#  required_for: [post_deployment_end]
#  parameters:
#    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/netconfig/configure_default_route.pp
#    puppet_modules: /etc/puppet/modules
#    timeout: 3600
#    cwd: /

